site_name: 'python-app-5'
site_description: 'Main documentation for python-app-5'
repo_url: https://github.com/rubenpinzon-sketch/python-app-5
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  - redirects:
      redirect_maps:
        'index.md': 'overview/what-is-backstage.md'

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting started: 'docs/index.md.md'